model_type: LogisticRegression
target_column: fulltime_result

input_features:
  - home_goals_avg
  - away_goals_avg
  - home_form
  - away_form
  - head_to_head
  - possession_avg
  - shots_on_target_avg
  - corner_kicks_avg

hyperparameters:
  max_iter: 1000
  random_state: 42
  solver: lbfgs
  C: 1.0
